# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be61c9fbfeace1ef0d7f7058e1fcf2fe"
name = "nat-go"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_files,write_files,read_content,write_content,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects"

[webhooks]
api_version = "2026-10"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
